### ISSUE TITLE
Clarify intent of hooks

### ISSUE THREAD

**Issue by zakangelle** [angelle-sw/use-axios-client#1]
I think for clarity's sake we should either remove the `axios` dependency and use native `fetch`, or change the hook names to `useAxios`/`useLazyAxios`.

**Comment by jpangelle** [comment]
Good suggestion

**Comment by jpangelle** [comment]
I’m leaning towards using `axios` but keeping the `fetch` name. Seems cleaner and gives us flexibility for changing HTTP clients in the future without breaking the names. Would this naming cause any confusion assuming we have proper documentation?

**Comment by zakangelle** [comment]
So I think the problem with keeping the `fetch` name is that `fetch` implies you are using the Fetch API, which could cause confusion with discoverability.

Also, if we are set on using `axios` internally, we are going to need to support `axios` [options](https://github.com/axios/axios#request-config), so ultimately the consumer will be made aware of the `axios` dependency either way. I just think it could be confusing to have something called `useFetch` and then say "if you need to configure this, here's the axios docs".

The other route you could go down is naming it something more generic like `useHttpRequest` - then you could make the `axios` dependency completely opaque by making a `options` facade that reflects the same configuration `axios` allows. For the record, I don't really like this route.

**Comment by zakangelle** [comment]
Going to close this as we got an official name now 🥇
