### ISSUE TITLE
Support SSR

### ISSUE THREAD

**Issue by zakangelle** [angelle-sw/use-axios-client#28]

**Comment by zakangelle** [comment]
A basic API sketch which adds a new prop called `initialData`:

```js
const { data, error, loading } = useAxios('https://reqres.in/api/things/1', {
  initialData: serverRequestedData,
});
```

If provided, the `useAxios` hook will _not_ initially fire a network request and will instead use the provided value as `data`.

In SSR implementations, this allows the consumer to write the hook in such a way that the first request is triggered and resolved server-side, and any subsequent requests are handled client-side.

This prop could also be called `initialValue` or even `ssrData`.

**Comment by therealparmesh** [comment]
Closing this issue because of https://github.com/angelle-sw/use-axios-client/pull/96.
