### ISSUE TITLE
Formalize consumer API

### ISSUE THREAD

**Issue by zakangelle** [angelle-sw/use-axios-client#39]
We should consider our API carefully before stamping our first major release.

One thing we could explore is the option of having a single hook with options vs. discrete hooks for different use cases.

A few options:

#### Single config object

```js
const { data, error, fetch, loading } = useAxios({
  url: 'https://example.com',
  lazy: true,
  method: 'get'
})
```

#### Axios options namespace

```js
const { data, error, fetch, loading } = useAxios({
  axiosOptions: {
    url: 'https://example.com',
    method: 'get'
  },
  lazy: true,
})
```

#### Discrete option hashes

```js
const { data, error, fetch, loading } = useAxios(
  { url: 'https://example.com', method: 'get' },
  { lazy: true }
)
```

**Comment by jpangelle** [comment]
We can keep them the API's separate for now.
