### ISSUE TITLE
Consider returning a retry/refetch function

### ISSUE THREAD

**Issue by zakangelle** [angelle-sw/use-axios-client#9]
Was thinking it may be nice for `useFetch` to return a `retry` or `refetch` function that can be called imperatively by the consumer.

This would account for the use case where an HTTP request fails and you want to show a "Retry" button that, when clicked, re-attempts the request.

```js
() => {
  const { data, error, retry } = useFetch('https://example.com');

  if (error) {
    return (
      <button onClick={retry}>retry</button>
    );
  }

  return (
    <>{data}</>
  );
}
```

Thoughts?

**Comment by jpangelle** [comment]
That’s a great idea. 🤓
